
version: '3'
services:
  # MongoDB Service
  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - clinic-network

  # Express.js App Service
  back-end:
    build: ./back-end
    container_name: containerBackEnd
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - clinic-network

  front-end:
    build: ./front-end
    ports:
      - "4200:4200"
    networks:
      - clinic-network
    volumes:
      - ./front-end/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - back-end

volumes:
  mongo-data:
networks:
  clinic-network:
    driver: bridge

